services:

  vector:
    image: timberio/vector:${VECTOR_TAG:-latest-distroless}
    command: --config /config/config.toml
    network_mode: host
    logging:
      driver: ${LOGGING_DRIVER:-local}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/config/config.toml
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS:-0.0.0.0:7000"}
      LOKI_ENDPOINT: ${LOKI_ENDPOINT:-http://loki:3100"}